name: Push to Huggingface

on:
  push:
    branches:
      - main

jobs:
  push_to_huggingface:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Install Git LFS
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - name: Set Remote URL
      env:
        HUGGINGFACE_USERNAME: ${{ secrets.HUGGINGFACE_USERNAME }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        HUGGINGFACE_REPO_NAME: ${{ secrets.HUGGINGFACE_REPO_NAME }}
      run: |
        git remote add hf https://$HUGGINGFACE_USERNAME:$HUGGINGFACE_TOKEN@huggingface.co/spaces/$HUGGINGFACE_USERNAME/$HUGGINGFACE_REPO_NAME
    - name: Push to Huggingface
      run: |
        git push hf main --force
